### ISSUE TITLE
version 3.5.1 rebuild

### ISSUE THREAD

**Issue by achimgaedke** [iterative/dvc-exe#100]
There's a version https://s3-us-east-2.amazonaws.com/dvc-public/dvc-pkgs/exe/dvc-3.5.0.exe but the download link on https://dvc.org/ points to 3.4.0... and 3.5.1 isn't built yet.

Looking at the [scoop installer](https://scoop.sh/) and its auto-updater config

https://github.com/ScoopInstaller/Main/blob/master/bucket/dvc.json

The last auto-update run resulted in:

https://github.com/ScoopInstaller/Main/actions/runs/5515796134/jobs/10056490074#step:3:403

> dvc: 3.5.1 (scoop version is 3.4.0) autoupdate available
> Autoupdating dvc
> Downloading dvc-3.5.1.exe to compute hashes!
> The remote server returned an error: (404) Not Found.
> URL https://s3-us-east-2.amazonaws.com/dvc-public/dvc-pkgs/exe/dvc-3.5.1.exe is not valid
> ERROR Could not update dvc, hash for dvc-3.5.1.exe failed!

So the rebuild for 3.5.1 hasn't been triggered, 3.5.0 was rebuilt and not advertised on the homepage.

.... besides the rebuild missing here, the website probably needs an update...

What do you think the scoop installer should follow? github? or the homepage?

**Comment by efiop** [comment]
Hi @achimgaedke . I think following a homepage is a safer choice.

**Comment by efiop** [comment]
3.5.1 should be ready in ~20 minutes.

**Comment by achimgaedke** [comment]
Yep, looks like DVC 3.5.1 is now built but the link on the dvc.org homepage is still outdated and points to 3.5.0.

**Comment by efiop** [comment]
@achimgaedke dvc.org is updated separately, https://github.com/iterative/dvc.org/pull/4691 . dvc.org has to wait until all packages are available (deb,rpm,osxpkg and exe), so a lag is expected. Would that be ok for scoop?

**Comment by achimgaedke** [comment]
Remembering from yesterday... everything else was 3.5, but Windows 3.4... I'll keep an eye on this before I remove the "Draft" from https://github.com/ScoopInstaller/Main/pull/4942 ...

Would be great to get eventually to the bottom of it, but scoop is up to date at the moment...
